on: 
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
 contents: read
jobs:
  plan:
    name: fmt/validate/plan
    runs-on: hulk
    defaults:
      run:
        working-directory: ./todoapp_infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          
      - name: Setup Azure CLI
        uses: azure/setup-azure@v3
        with:
          version: latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          auth-type: SERVICE_PRINCIPAL

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Fmt
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: todoapp_infra/tfplan
