name: "surya"

on: workflow_dispatch

jobs: 
  terraform-job:  
    runs-on: hulk
    steps:
        - name: Checkout
          uses: actions/checkout@v5.0.0
 
        - name: Install Terraform
          uses: little-core-labs/install-terraform@v2.0.0
          with: 
              version: 1.8.5
              
        - name: Azure Login
          uses: Azure/login@v2.3.0
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            client-secret: ${{ secrets.AZURE_CLIENT_SECRET }} 
                  
            
        
